### ISSUE TITLE
Decide what fields are needed for personal information

### ISSUE THREAD

**Issue by gvwilson** [tammy-dg/DNA-doh#5]
1.  Age: uniform from age 1 to age 90 (?).
2.  Gender: male 47%, female 48%, non-binary 4%, NA 1%.
3.  Weight (since it is a factor in so many conditions).
    - Increases with age up to age 18 (or 20, or 25).
    - Increases more slowly after that to age 75.
    - Declines gently after age 75.
    - How wide a band around the mean?
    - Should it be correlated with some allele(s)?
4.  Presence of diabetes.
    - Increases slowly with age.
    - Correlates with being above-average weight for age.
    - Should correlate with some allele(s).
5.  Presence of Noone's Syndrome (made up).
    - Correlates completely with a single allele.
    - Probability of manifesting goes from 0% at age 25 to 100% at age 50.
6.  Taste in music.
    - Starts at zero.
    - Ramps down to negative at age 15.
    - Ramps up to positive at age 50.
    - Ramps down to zero at age 90.
    - No genetic component, but lows are lower for males.

**Comment by tammy-dg** [comment]
Some thoughts:
* I'm not sure how realistic you want to be, but for example UK Biobank participants are limited to 40-69 y/o. Personally, I don't think we have to have the same restriction on our population here.
* I like having a gender column, and realistic representation of gender identities :). We should also include "genetic sex", though.
* I think we can just follow a normal distribution of weight?
* Does diabetes mean both T1 and T2 here?
* Are you trying to say that teenagers have dismal taste in music? 😢

**Comment by gvwilson** [comment]
1. I'm happy restricting the population to adults - it makes the weight calculations a lot easier (no need for piecewise if we're looking at age 25-75).
2. If we're doing genetic sex, are we including XXY and the like?
3. :+1: for a normal distribution of weights if subjects are all adults.
4. Should we use diabetes at all, or stick to lycanthropy and other made-up ailments?
5. Yes.
